### ISSUE TITLE
Microphone stream 

### ISSUE THREAD

**Issue by jernejc** [gntikos/cordova-BluetoothSco#1]
Could this potentially stream microphone live to Bluetooth?

**Comment by gntikos** [comment]
I don't really understand your question.
I use this plugin in a personal project to record audio from a
Bluetooth headset (instead of the internal microphone). Is this what you mean?

**Comment by jernejc** [comment]
Hey, thanks for the quick reply.
I would need the sound to travel the other way around. So from the microphone to bluetooth?

**Comment by gntikos** [comment]
Well, in theory it should work this way too, as long some output stream
restrictions are met. I'm not sure but I think that the stream type must be
STREAM_VOICE_CALL.

2014-10-23 11:51 GMT+03:00 Jernej notifications@github.com:

**Comment by jernejc** [comment]
Great, I will give it a go, and report back. 
Thanks again for the quick responses.

**Comment by jernejc** [comment]
Ok, so I ended up with this:
https://github.com/jernejc/cordova-BluetoothSco/blob/master/src/android/BluetoothSco.java

Added STREAM_VOICE_CALL and MODE_CALL at line 110/111, and also added an AudioRecorder after SCO is successfully connected, just to turn on the mic and hopefully stream ( line 80+ ). The AudioRecorder is also where I limited the stream, but it doesn't get transmitted to the bluetooth module. I can hear the slight hum from the speakers, probably the recorder, but no actual sound gets through.

Do you maybe see any stupid mistakes I made, I have zero experience with JAVA or Android SDK.

By the way. I get a success callback from the function and CONNECTED status.

**Comment by gntikos** [comment]
Well I don't have much experience with Android SDK either. I can't test your code now, but I plan
to add some functionality for audio playback in the next 2-3 days.

**Comment by jernejc** [comment]
Ok, great!

**Comment by gntikos** [comment]
You can now pass an option to enable playback through Bluetooth. Your call should be like

``` js
BluetoothSco.start(function() {
  alert('Bluetooth SCO on.');
}, function(error) {
  alert('Bluetooth SCO on error: ' + error);
}, {enablePlayback: true});
```

Closing issue.
